
version: '2'

services:
  
  # Base image.
  baseimage:
    build: ./baseimage
    image: hyperledger/fabric-baseimage:latest


  vp0:
    extends:
      file: compose-defaults.yml
      service: vp
    ports:
      - "7050:7050" # Default REST API: https://github.com/hyperledger/fabric/blob/master/peer/core.yaml
      - "7051:7051"
      - "7053:7053"
    environment:
      - CORE_PEER_ID=vp0
      - CORE_PEER_DISCOVERY_PERIOD=1s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=1s
      - CORE_SECURITY_ENABLED=false


  vp1:
    extends:
      file: compose-defaults.yml
      service: vp
    ports:
      - "8050:7050"
      - "8051:7051"
      - "8053:7053"
    environment:
      - CORE_PEER_ID=vp1
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_SECURITY_ENABLED=false
    links:
      - vp0


  vp2:
    extends:
      file: compose-defaults.yml
      service: vp
    ports:
      - "9050:7050"
      - "9051:7051"
      - "9053:7053"
    environment:
      - CORE_PEER_ID=vp2
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_SECURITY_ENABLED=false
    links:
      - vp0


  vp3:
    extends:
      file: compose-defaults.yml
      service: vp
    ports:
      - "10050:7050"
      - "10051:7051"
      - "10053:7053"
    environment:
      - CORE_PEER_ID=vp3
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_SECURITY_ENABLED=false
    links:
      - vp0

